# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16bf5c8e4f06803e28ff912f1919f1ac3e2a47555775d8fd8f281a0a885c6da662eaaf20ffbf147573770f45576af8f0795a3481e78afd626253b8aacd6d8fb1

test:
  secret_key_base: eb83fef443b6956757dfce46c27c3039d1ed7cc4e4a2607380b45118a0aadb0f014fd8a9cacdb110aa4e41a85616c6e671a0f427f438cc552edb16ab4c81894b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
